### PR TITLE
Add nullability annotations

### PR DESCRIPTION
**Pull request by freya022**

### CODE REVIEW

**Comment by felldo** [comment]
I think it's better to add a dependency on `compileOnly("org.jspecify:jspecify:0.3.0")`.
It is pretty widely supported and saves us pretty much all annotations. While in your case you could use `@ParametersAreNonnullByDefault` on the `package-info` file, it doesn't help with return types and afaik it is not possible to mark generic parameters an non null.

Therefore I suggest to add the mentioned dependency instead and add a `package-info.java` file which contains the following:
```java
@NullMarked
package net.fellbaum.jemoji;

import org.jspecify.annotations.NullMarked;
```
With this all types should be declared a NonNull if not otherwise marked as Nullable

**Comment by freya022** [comment]
At least `jspecify` annotations works with Kotlin so, alright, but it's quite weird how you can use them on generics, but they are still seen as platform types. Though using `@NullMarked` on the package does help for generics too

**Comment by freya022** [comment]
Last question though: Do we keep the dependency `compileOnly`? When looking at the sources, the annotation is not present in the classpath, and so, creates errors.

I think adding a 3 KB dependency isn't too much

**Comment by felldo** [comment]
> I don't like implicit non-null, I'd rather have either NotNull/Nonnull, or Nullable on the returned types and parameters.

I partially agree with this in a Java context, but imo null annotations can clutter the code quite a bit. This is a completely null free library and if a null value is returned it is a bug. For that reason I don't think it is a big deal to just specify that everything returns NonNull in the package info.
Btw. why did you add a `@Nullable` to the parameters? Even if the null case is handled, it is not really a "valid" argument to pass as you will never get something different than an empty string/collection/optional an therefore shouldn't be Nullable.

> Last question though: Do we keep the dependency `compileOnly`? When looking at the sources, the annotation is not present in the classpath, and so, creates errors.
> 
> I think adding a 3 KB dependency isn't too much

For that case I think we can add the dependency as `compileOnlyApi` though I am not 100% sure if this is the right thing to do. You can test if it resolves this issue, otherwise I would keep it as `compileOnly`.

**Comment by freya022** [comment]
Issues solved

**Review by felldo — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
